#PROD: Stop Analyze   API
https://oyster-app-r8vhv.ondigitalocean.app/api/stop

###TEST: Stop Analyze   API
http://localhost:3000/api/stop

###PROD: Start process and configure it  PROD
POST https://oyster-app-r8vhv.ondigitalocean.app/api/start HTTP/1.1
content-type: application/json

{
  "symbol": "BTCUSDT",
  "interval": "1m"
}

###PROD: Stop process and configure it  PROD
POST https://oyster-app-r8vhv.ondigitalocean.app/api/stop  HTTP/1.1
content-type: application/json

{
  "symbol": "BTCUSDT",
  "interval": "1m"
}


### TEST:Start process and configure it  TEST

POST http://localhost:3000/api/start HTTP/1.1
content-type: application/json

{
  "symbol": "BTCUSDT",
  "interval": "1m"
}

### TEST:Stop  TEST

POST http://localhost:3000/api/stop HTTP/1.1
content-type: application/json

{
  "symbol": "BTCUSDT",
  "interval": "1m"
}
