#PROD: Stop Analyze   API
https://oyster-app-r8vhv.ondigitalocean.app/api/stop

###TEST: Stop Analyze   API
http://localhost:3000/api/stop

###PROD: Start process and configure it  PROD
POST https://oyster-app-r8vhv.ondigitalocean.app/api/start HTTP/1.1
content-type: application/json

{
  "symbol": "BTCUSDT",
  "interval": "1m"
}

###PROD: Stop process and configure it  PROD
POST https://oyster-app-r8vhv.ondigitalocean.app/api/stop  HTTP/1.1
content-type: application/json

{
  "symbol": "BTCUSDT",
  "interval": "1m"
}


### TEST:Start process and configure it  TEST

POST http://localhost:3000/api/start HTTP/1.1
content-type: application/json

{
  "symbol": "BTCUSDT",
  "interval": "1m"
}

### TEST:Stop  TEST

POST http://localhost:3000/api/stop HTTP/1.1
content-type: application/json

{
  "symbol": "BTCUSDT",
  "interval": "1m"
}

### TEST:Create Order  TEST
POST http://localhost:3000/api/orders HTTP/1.1
content-type: application/json

{
  "symbol": "RUNEBUSD",
  "quantity": "6",
  "price": "2.2"
}


### TEST:Create Order  TEST2ndl
POST http://localhost:3000/api/orders HTTP/1.1
content-type: application/json

{
  "symbol": "RUNEBUSD",
  "quantity": "6",
  "price": "5.5"
}

### TEST:Create Order SELL TEST2
POST http://localhost:3000/api/orders/sell HTTP/1.1
content-type: application/json

{
  "symbol": "RUNEBUSD",
  "quantity": "6",
  "price": "5.44"
}

### TEST:Cancel Order  TEST
POST http://localhost:3000/api/orders/cancel HTTP/1.1
content-type: application/json

{
  "symbol": "RUNEBUSD",
  "orderId": "848663"
}

### TEST:Get Order
GET http://localhost:3000/api/orders/794186 HTTP/1.1
