export const WAVE_ANALYZER_QUEUE =  Symbol('WAVE_ANALYZER_QUEUE');
export const WAVE_ANALYZER_QUEUE_SERVICE =  Symbol('WAVE_ANALYZER_QUEUE_SERVICE');
export const WAVE_ANALYZER_EVENT_PUBLISHER =  Symbol('WAVE_ANALYZER_EVENT_PUBLISHER');
